"""User-facing interface text, in English and Russian.

Everything vmpc prints *about itself* — command descriptions, ``/status``
labels, ``/help``, error and confirmation messages — lives here instead of
inline in the modules that print it. ``/lang`` switches only this: what
language vmpc speaks about itself. It has nothing to do with what language
the model replies in — the base system prompt already tells the model to
follow the user's language on its own, and that is a separate concern from
whether "no endpoint configured" reads in English or Russian.

Keys are dotted by where they appear (``status.mode``, ``err.no_endpoint``)
so a duplicate key is a copy-paste bug you can grep for, not a silent
overwrite. A key missing from the active language falls back to English,
and a key missing from English too returns the key itself — a visibly wrong
string is a bug report; a crash is not.
"""

from __future__ import annotations

#: The language vmpc's own text is in right now. Read by :func:`t`, written
#: by :func:`set_ui_language`. A module-level global rather than something
#: threaded through every call site: vmpc is single-session and
#: single-threaded, and passing a language argument through every ``Text()``
#: call in the codebase would touch the same 212 lines this module exists to
#: avoid touching twice.
CURRENT: str = "en"

#: What ``/lang`` accepts and what ``/status`` shows for it.
LANGUAGE_NAMES: dict[str, str] = {"en": "English", "ru": "Русский"}


def set_ui_language(language: str) -> None:
    """Switch vmpc's own interface text. Falls back to English on a bad code."""
    global CURRENT
    CURRENT = language if language in LANGUAGE_NAMES else "en"


def current_language() -> str:
    """The active interface language code.

    A function rather than reading :data:`CURRENT` via ``from vmpc.strings
    import CURRENT`` — that form copies the value at import time and would
    never see a later :func:`set_ui_language` call, since Python names bind
    to the object, not to the module attribute.
    """
    return CURRENT


def en_plural(n: int, singular: str, plural: str | None = None) -> str:
    """``1 file`` vs ``2 files``. ``plural`` defaults to ``singular + "s"``."""
    return singular if n == 1 else (plural if plural is not None else f"{singular}s")


def ru_plural(n: int, one: str, few: str, many: str) -> str:
    """Russian has three plural forms, not two: 1 файл, 2–4 файла, 5+ файлов.

    The rule (standard Russian grammar, not a vmpc invention): numbers ending
    in 11–14 always take ``many`` regardless of their last digit; otherwise
    the last digit decides — 1 takes ``one``, 2–4 take ``few``, everything
    else (0, 5–9) takes ``many``.
    """
    n = abs(n)
    if 11 <= n % 100 <= 14:
        return many
    last = n % 10
    if last == 1:
        return one
    if 2 <= last <= 4:
        return few
    return many


def t(key: str, **kwargs: object) -> str:
    """Look up ``key`` in the active language, formatting placeholders in.

    ``t("err.unknown_chat", target=target)`` rather than an f-string: the
    format call happens *after* the language lookup, so the same ``{target}``
    placeholder works whichever language's template ends up chosen.
    """
    table = _STRINGS.get(CURRENT, _STRINGS["en"])
    template = table.get(key)
    if template is None:
        template = _STRINGS["en"].get(key, key)
    return template.format(**kwargs) if kwargs else template


_STRINGS: dict[str, dict[str, str]] = {
    "en": {
        # -- vmpc/commands/__init__.py: command-table descriptions ----------
        "cmd.api": "add, switch or edit API endpoints",
        "cmd.model": "choose the model for the active endpoint",
        "cmd.context": "attach a folder or file for the model to read",
        "cmd.mode": "switch prompt mode, or write your own",
        "cmd.lang": "switch vmpc's own interface between English and Russian",
        "cmd.reasoning": "toggle streaming of the model's reasoning channel",
        "cmd.new": "start a fresh conversation",
        "cmd.chats": "reopen a saved conversation",
        "cmd.title": "rename this chat, or let the model name it again",
        "cmd.status": "show the active endpoint and token usage",
        "cmd.clear": "clear the screen and start fresh",
        "cmd.help": "list commands",
        "cmd.quit": "exit vmpc",
        "cmd.mode_toggle_suffix": "(on — type again to turn off)",
        "cmd.dev.raw": "the last reply's exact source, before rendering",
        "cmd.dev.render": "run markdown through the renderer and show the result",
        "cmd.dev.wire": "the exact HTTP request a turn would send, key masked",
        "cmd.dev.ping": "measure latency to first token and throughput",
        "cmd.dev.palette": "every theme style, and what this terminal supports",
        "cmd.dev.prompt": "the full system prompt currently in effect",
        # -- vmpc/modes.py ----------------------------------------------------
        "mode.dev.desc": "developer mode — terse answers, and the debugging commands",
        "mode.short.desc": "one paragraph, maximum",
        "mode.explain.desc": "teach the topic, with an example before the rule",
        "mode.err.empty_name": "name is empty",
        "mode.err.bad_name": "use lowercase letters, digits, - and _; start with a letter",
        "mode.err.taken": "/{name} is already a command",
        # -- vmpc/ui/app.py --------------------------------------------------
        "app.context_not_read": "  context not read: {exc}",
        "app.context_error": "  ✖ context: {problem}",
        "app.context_attached": "  ✿ context ",
        "app.context_files": "{n} {noun}",
        "app.context_from_paths": " from {n} {noun}",
        "app.input_error": "input error: {exc}",
        "app.bye": "  bye",
        "app.command_needs": "  {display} needs ",
        "app.unknown_command": "  unknown command {name}",
        "app.help_hint": "  /help — list commands",
        "app.not_implemented": "  {display} is not implemented yet",
        "app.no_endpoint": "  no endpoint configured",
        "app.api_add_hint": "  /api add — configure one",
        "app.provider_problem": "  {name}: {problem}",
        "app.api_edit_hint": "  /api edit — fix it",
        "app.interrupted": "  interrupted",
        "app.empty_response": "  (empty response)",
        "app.chat_not_saved": "  chat not saved: {exc}",
        "app.error_prefix": "  ✖ {error}",
        "app.error_hint": "    {hint}",
        "app.banner_no_endpoint": "no endpoint yet — run ",
        "app.banner_for_commands": " for commands",
        "app.banner_attached": "  attached",
        "app.placeholder_no_endpoint": "run /api to configure an endpoint",
        "app.placeholder_ready": "ask anything · / for commands",
        "app.working_header": "Working",
        # -- vmpc/commands/builtins.py ---------------------------------------
        "help.commands_header": "commands",
        "help.modes_header": "modes",
        "help.group_unlocks": " unlocks {n} more {noun}",
        "help.command_noun": "command",
        "help.key_enter": "  enter",
        "help.key_enter_desc": "      send",
        "help.key_alt_enter": "  alt+enter",
        "help.key_alt_enter_desc": "  newline",
        "help.key_esc": "  esc",
        "help.key_esc_desc": "        interrupt a running turn",
        "help.key_ctrl_c": "  ctrl+c",
        "help.key_ctrl_c_desc": "     clear the input, twice to quit",
        "status.not_set": "(not set)",
        "status.none": "(none)",
        "status.unnamed": "(unnamed)",
        "status.on": "on",
        "status.off": "off",
        "status.label.endpoint": "endpoint",
        "status.label.format": "format",
        "status.label.url": "url",
        "status.label.model": "model",
        "status.label.api_key_type": "api-key-type",
        "status.label.api_key": "api-key",
        "status.label.auth": "auth",
        "status.label.reasoning": "reasoning",
        "status.label.mode": "mode",
        "status.label.language": "language",
        "status.label.chat": "chat",
        "status.label.context": "context",
        "status.label.messages": "messages",
        "status.label.tokens": "tokens",
        "status.context_none": "(none)",
        "new.conversation": "  new conversation",
        "lang.unknown": "  unknown language {wanted!r} — try en, ru or auto",
        "lang.set": "  interface language ",
        "lang.auto_label": "auto — follows the system default",
        # -- vmpc/commands/mode.py -------------------------------------------
        "mode.custom_suffix": "  custom",
        "mode.menu_hint": "  ·  /mode edit NAME  ·  /mode remove NAME  ·  /mode off",
        "mode.no_mode_named": "  no mode named {name!r}",
        "mode.list_hint": " — list them",
        "mode.unlocks_label": "  unlocks  ",
        "mode.no_prompt_placeholder": "(no prompt — the default one is used as-is)",
        "mode.unlocked_hint": "  new commands unlocked — ",
        "mode.already_default": "  already on the default prompt",
        "mode.off": "  mode off",
        "mode.off_suffix": " — back to the default prompt",
        "mode.field_name": "name",
        "mode.field_name_placeholder": "reviewer",
        "mode.field_description": "description",
        "mode.field_description_placeholder": "what this mode is for",
        "mode.field_prompt": "prompt",
        "mode.field_prompt_placeholder": "how the model should answer",
        "mode.default_description": "custom mode",
        "mode.cancelled_no_prompt": "  cancelled — a mode with no prompt would do nothing",
        "mode.confirm_unlock_dev": "Unlock the developer commands in this mode?",
        "mode.saved": " saved — type it to switch",
        "mode.built_in": "  /{name} is built in — ",
        "mode.write_own_hint": " to write your own",
        "mode.no_custom_named": "  no custom mode named {name!r}",
        "mode.cancelled_empty_prompt": "  cancelled — empty prompt",
        "mode.updated": "  ✔ /{name} updated",
        "mode.removed": "  removed /{name}",
        # -- vmpc/commands/model.py ------------------------------------------
        "model.picker_add_label": "+ type a name",
        "model.picker_add_desc": "add it by hand",
        "model.picker_probe_label": "⌕ probe",
        "model.picker_probe_desc": "try known names against this key",
        "model.picker_scan_label": "↻ ask the endpoint",
        "model.picker_scan_desc": "retry GET /models",
        "model.picker_title": "Model for {name}",
        "model.set": "  model ",
        "model.field_model": "model:",
        "model.field_model_placeholder": "the exact name the endpoint expects",
        "model.already_saved": "  already saved: {name}",
        "model.saved_on": "  saved on ",
        "model.which_one": "  which one? /model rm NAME",
        "model.not_saved": "  not saved: {name}",
        "model.forgot": "  forgot ",
        "model.still_using": "  still using it — ",
        "model.to_switch": " to switch",
        "model.nothing_saved": "  nothing saved, and the endpoint did not answer",
        "model.saved_label": "saved",
        "model.advertised_label": "advertised",
        "model.did_not_advertise": "  {name} did not advertise a model list",
        "model.probe_hint": "  /model probe — find out by asking",
        "model.new_label": " new",
        "model.advertised_sep": " advertised · ",
        "model.probe_header": "  probe ",
        "model.probe_against": " names against ",
        "model.probe_requests": "{n} requests, one token each · esc to stop",
        "model.confirm_send": "Send them?",
        "model.cancelled": "  cancelled",
        "model.stopping_key": "    stopping — that answer is about the key, not the name",
        "model.too_many_failures": "    too many failures — stopping",
        "model.saved_summary": "  saved ",
        "model.using_sep": " · using ",
        "model.asked": "{n} asked",
        "model.label.available": "available",
        "model.label.rejected": "rejected",
        "model.label.unclear": "unclear",
        "model.label.failed": "failed",
        "model.label.not_sent": "not sent",
        "model.cannot_read": "  ✖ cannot read {path}: {exc}",
        # -- vmpc/ui/picker.py ------------------------------------------------
        "picker.select_hint": "↑↓ move · enter select · esc cancel",
        "picker.multiline_hint": "alt+enter for a newline · enter to finish · esc cancel",
        "picker.confirm_hint": "enter confirm · esc cancel",
        "picker.yes": "yes",
        "picker.no": "no",
        # -- vmpc/config.py: wire/key/auth descriptions ----------------------
        "wire_desc.openai": "/chat/completions, SSE deltas — OpenAI, Groq, together, vLLM, LM Studio, OpenRouter",
        "wire_desc.anthropic": "/v1/messages, typed SSE events — Anthropic, Bedrock gateways, proxies",
        "keytype_desc.static": "the key is stored in the config file",
        "keytype_desc.env": "read from an environment variable at request time",
        "keytype_desc.command": "run a shell command and use its stdout (1Password, pass, vault)",
        "auth_desc.raw_suffix": "key already carries its own scheme",
        "auth_desc.none": "no auth header — local endpoints, or auth via a proxy",
        # -- vmpc/commands/api.py ---------------------------------------------
        "api.unknown_verb": "unknown: /api {verb}",
        "api.try_hint": "  try: add · list · use · edit · remove · test",
        "api.menu_add": "add",
        "api.menu_add_desc": "configure a new endpoint",
        "api.menu_use": "use",
        "api.menu_use_desc": "switch the active endpoint",
        "api.menu_edit": "edit",
        "api.menu_edit_desc": "change an existing endpoint",
        "api.menu_test": "test",
        "api.menu_test_desc": "send a one-token request to verify it works",
        "api.menu_remove": "remove",
        "api.menu_remove_desc": "delete an endpoint",
        "api.menu_title": "API endpoints",
        "api.cancelled": "  cancelled",
        "api.saved_to": "  saved to {path}",
        "api.summary_added": "added",
        "api.summary_updated": "updated",
        "api.edit_which": "Edit which endpoint?",
        "api.use_which": "Use which endpoint?",
        "api.remove_which": "Remove which endpoint?",
        "api.test_which": "Test which endpoint?",
        "api.field_site": "site:",
        "api.field_api_key": "api-key:",
        "api.key_placeholder_editing": "sk-… (hidden; ctrl+v pastes; enter keeps the current key)",
        "api.key_placeholder_new": "sk-… (hidden; ctrl+v pastes)",
        "api.field_env_var": "env var:",
        "api.field_command": "command:",
        "api.step_wire_title": "API format",
        "api.step_keytype_title": "api-key-type",
        "api.step_auth_title": "auth",
        "api.field_header_name": "header name:",
        "api.field_model": "model:",
        "api.field_name": "name:",
        "api.field_name_placeholder": "how this endpoint appears in /api list",
        "api.field_extra_headers": "extra headers:",
        "api.field_extra_headers_placeholder": "optional — name: value, comma separated",
        "api.incomplete": "  incomplete: {problem}",
        "api.confirm_save_anyway": "Save anyway?",
        "api.active_label": "  active: ",
        "api.confirm_remove": "Remove {name}?",
        "api.removed": "  removed {name}",
        "api.not_usable": "  not usable: {problem}",
        "api.testing_arrow": "  → {url}",
        "api.test_empty_response": "(empty response)",
        "api.no_endpoints": "  no endpoints configured",
        "api.label.site": "site",
        "api.label.extra_headers": "extra headers",
        "api.err.not_url": "that does not look like a URL",
        "api.err.must_http": "URL must be http or https",
        "api.err.drop_v1": "drop the /v1 for the Anthropic format; it is added automatically",
        "api.err.header_format": "expected 'name: value' but got {part!r}",
        "api.err.missing_header_name": "missing a header name in {part!r}",
        "api.err.missing_header_value": "не указано значение для {name!r}",
        # -- vmpc/commands/chats.py -------------------------------------------
        "chats.unknown": "  unknown: /chats {action}",
        "chats.hint": "  ·  /chats list  ·  /chats rm",
        "title.rename_label": "  /title NAME",
        "title.rename_desc": "  rename  ·  ",
        "title.auto_hint": "/title auto",
        "title.auto_desc": "  ask the model again",
        "title.no_name_yet": "  this chat has no name yet",
        "title.no_name_hint": " — or send a message and one is written for you",
        "title.empty_after_clean": "  that leaves nothing to file it under",
        "chats.no_saved": "  no saved chats yet",
        "chats.turn": "turn",
        "chats.open_title": "open a chat",
        "chats.cannot_open": "  cannot open that chat: {exc}",
        "chats.needs_app": "  /chats needs the interactive app",
        "chats.restored": "{n} {turn_noun} restored · {tokens} tokens",
        "chats.prompt_label": "  prompt  ",
        "chats.naming": "  naming…",
        "chats.nothing_to_name": "  nothing to name yet — ask something first",
        "chats.bad_name_response": "  the endpoint did not return a usable name",
        "chats.delete_title": "delete a chat",
        "chats.no_match": "  no chat matching {target!r}",
        "chats.confirm_delete": "Delete {label!r}?",
        "chats.deleted": "  deleted {label}",
        "chats.delete_failed": "  could not delete that chat",
        "chats.ago_just_now": "just now",
        "chats.ago_minutes": "{n}m ago",
        "chats.ago_hours": "{n}h ago",
        "chats.ago_days": "{n}d ago",
        # -- vmpc/context.py --------------------------------------------------
        "ctx.reason.over_file_limit": "over the file limit",
        "ctx.reason.binary": "binary",
        "ctx.reason.secret": "looks like a secret",
        "ctx.reason.budget": "budget",
        "ctx.reason.unreadable": "unreadable ({detail})",
        "ctx.reason.empty": "empty",
        "ctx.reason.too_big": "too big",
        "ctx.err.not_file_or_folder": "{path} is not a file or a folder",
        "ctx.err.no_path": "no path given",
        "ctx.err.cannot_resolve": "cannot resolve {target}: {exc}",
        "ctx.err.does_not_exist": "{path} does not exist",
        "ctx.err.budget_full": "the context budget is already full",
        # -- vmpc/commands/context.py -----------------------------------------
        "ctx.which_folder": "  which folder? /context PATH",
        "ctx.already_attached": "  already attached: {path}",
        "ctx.which_one": "  which one? /context rm PATH",
        "ctx.not_attached": "  not attached: {path}",
        "ctx.nothing_attached": "  nothing attached",
        "ctx.hint_path": "PATH — read a folder or a file",
        "ctx.detached": "  detached ",
        "ctx.header_context": "context",
        "ctx.header_reloaded": "context reloaded",
        "ctx.skipped_label": "  │   skipped ",
        "ctx.budget_ran_out": "the budget ran out — not all of it is attached",
        "ctx.tokens_added": " added to every turn · ",
        "ctx.clear_hint": "/context clear",
        "ctx.to_detach": " to detach",
        # -- vmpc/commands/dev.py ---------------------------------------------
        "dev.no_role_message": "  no {role} message that far back",
        "dev.chars_lines": "{chars} chars, {n} {line_noun}",
        "dev.line": "line",
        "dev.no_reply_rerender": "  no reply to re-render",
        "dev.render_header": "  render ",
        "dev.sample_label": "sample",
        "dev.last_reply_label": "last reply",
        "dev.width_label": " · width {width}",
        "dev.post_label": "  POST ",
        "dev.via_label": "  via  ",
        "dev.transport_sdk": "vendor SDK",
        "dev.transport_httpx": "httpx",
        "dev.credential_error": "  ✖ credential: {detail}",
        "dev.ping_header": "  ping ",
        "dev.no_content": "  ✖ no content came back",
        "dev.label.total": "total",
        "dev.label.first_token": "first token",
        "dev.label.throughput": "throughput",
        "dev.label.output": "output",
        "dev.output_value": "{tokens} tokens, {chars} chars",
        "dev.palette.color_system": "color system",
        "dev.palette.no_color": "no_color",
        "dev.palette.terminal": "terminal",
        "dev.palette.legacy_windows": "legacy windows",
        "dev.palette.width": "width",
        "dev.prompt_header": "  system prompt",
        "dev.prompt_chars": "  {n} chars",
        "dev.mode_label": "  mode  ",
        "dev.mode_none": "(none — default prompt only)",
        "dev.files_label": "  files ",
        # -- vmpc/cli.py -------------------------------------------------------
        "cli.no_terminal": "vmpc: the interactive mode needs a terminal.\n  run 'vmpc' directly in a terminal, or use a subcommand:\n    vmpc chat \"your question\"\n    vmpc api list",
        "cli.no_endpoint_named": "vmpc: no endpoint named {name!r}",
        "cli.no_saved_chat_matching": "vmpc: no saved chat matching {what!r}",
        "cli.nothing_to_send": "vmpc: nothing to send",
        "cli.no_endpoint_configured": "vmpc: no endpoint configured — run 'vmpc api add'",
        "cli.provider_problem": "vmpc: {name}: {problem}",
        "cli.error_prefix": "vmpc: {error}",
        "cli.error_hint": "  {hint}",
        "cli.context_problem": "vmpc: context: {problem}",
        "cli.api_needs_terminal": "vmpc: {label} asks questions, so it needs a terminal.\n  these work anywhere:\n    vmpc api list\n    vmpc api test NAME",
        "cli.endpoint_menu_label": "the endpoint menu",
        "cli.no_endpoint_short": "no endpoint configured",
        "cli.unknown_models_action": "vmpc: unknown 'models' action {action!r}",
        "cli.did_not_advertise": "{name} did not advertise a model list",
        "cli.models_probe_hint": "  vmpc models probe",
        "cli.models_probe_hint_suffix": "  — find out by asking",
        "cli.probe_needs_terminal": "vmpc: 'models probe' asks before sending, so it needs a terminal.\n  run it in a terminal, or use '/model probe' inside vmpc",
        "cli.which_chat": "vmpc: which chat? pass an id from 'vmpc chats'",
        "cli.no_saved_chat": "vmpc: no saved chat matching {target!r}",
        "cli.could_not_delete": "vmpc: could not delete {id}",
        "cli.deleted": "deleted {label}",
        "cli.unknown_chats_action": "vmpc: unknown 'chats' action {action!r}",
        "cli.no_saved_chats": "no saved chats yet",
        # -- vmpc/streaming/controller.py -------------------------------------
        "stream.thinking": "Thinking",
        # -- vmpc/render/status.py --------------------------------------------
        "status.interrupt_hint": "Esc to interrupt",
        "status.tok_suffix": " tok",
    },
    "ru": {
        # -- vmpc/commands/__init__.py: command-table descriptions ----------
        "cmd.api": "добавить, переключить или изменить API-эндпоинты",
        "cmd.model": "выбрать модель для активного эндпоинта",
        "cmd.context": "подключить папку или файл для чтения моделью",
        "cmd.mode": "переключить режим промпта или написать свой",
        "cmd.lang": "переключить интерфейс vmpc между английским и русским",
        "cmd.reasoning": "переключить стриминг канала рассуждений модели",
        "cmd.new": "начать новый разговор",
        "cmd.chats": "открыть сохранённый разговор",
        "cmd.title": "переименовать чат или дать модели назвать его заново",
        "cmd.status": "показать активный эндпоинт и расход токенов",
        "cmd.clear": "очистить экран и начать заново",
        "cmd.help": "список команд",
        "cmd.quit": "выйти из vmpc",
        "cmd.mode_toggle_suffix": "(включён — наберите ещё раз, чтобы выключить)",
        "cmd.dev.raw": "точный исходник последнего ответа, до рендера",
        "cmd.dev.render": "прогнать markdown через рендерер и показать результат",
        "cmd.dev.wire": "точный HTTP-запрос хода, ключ скрыт",
        "cmd.dev.ping": "измерить задержку до первого токена и пропускную способность",
        "cmd.dev.palette": "все стили темы и что поддерживает этот терминал",
        "cmd.dev.prompt": "полный системный промпт, действующий сейчас",
        # -- vmpc/modes.py ----------------------------------------------------
        "mode.dev.desc": "режим разработчика — короткие ответы и отладочные команды",
        "mode.short.desc": "максимум один абзац",
        "mode.explain.desc": "объяснить тему с примером перед правилом",
        "mode.err.empty_name": "имя пустое",
        "mode.err.bad_name": "используйте строчные буквы, цифры, - и _; начните с буквы",
        "mode.err.taken": "/{name} уже занято командой",
        # -- vmpc/ui/app.py --------------------------------------------------
        "app.context_not_read": "  контекст не прочитан: {exc}",
        "app.context_error": "  ✖ контекст: {problem}",
        "app.context_attached": "  ✿ контекст ",
        "app.context_files": "{n} {noun}",
        "app.context_from_paths": " из {n} {noun}",
        "app.input_error": "ошибка ввода: {exc}",
        "app.bye": "  пока",
        "app.command_needs": "  {display} требует ",
        "app.unknown_command": "  неизвестная команда {name}",
        "app.help_hint": "  /help — список команд",
        "app.not_implemented": "  {display} пока не реализована",
        "app.no_endpoint": "  эндпоинт не настроен",
        "app.api_add_hint": "  /api add — настроить эндпоинт",
        "app.provider_problem": "  {name}: {problem}",
        "app.api_edit_hint": "  /api edit — исправить",
        "app.interrupted": "  прервано",
        "app.empty_response": "  (пустой ответ)",
        "app.chat_not_saved": "  чат не сохранён: {exc}",
        "app.error_prefix": "  ✖ {error}",
        "app.error_hint": "    {hint}",
        "app.banner_no_endpoint": "эндпоинт не настроен — выполните ",
        "app.banner_for_commands": " — список команд",
        "app.banner_attached": "  подключено",
        "app.placeholder_no_endpoint": "выполните /api, чтобы настроить эндпоинт",
        "app.placeholder_ready": "спросите что угодно · / для команд",
        "app.working_header": "Думаю",
        # -- vmpc/commands/builtins.py ---------------------------------------
        "help.commands_header": "команды",
        "help.modes_header": "режимы",
        "help.group_unlocks": " открывает ещё {n} {noun}",
        "help.command_noun": "команду",
        "help.key_enter": "  enter",
        "help.key_enter_desc": "      отправить",
        "help.key_alt_enter": "  alt+enter",
        "help.key_alt_enter_desc": "  новая строка",
        "help.key_esc": "  esc",
        "help.key_esc_desc": "        прервать выполнение",
        "help.key_ctrl_c": "  ctrl+c",
        "help.key_ctrl_c_desc": "     очистить ввод, дважды — выйти",
        "status.not_set": "(не задано)",
        "status.none": "(нет)",
        "status.unnamed": "(без названия)",
        "status.on": "вкл",
        "status.off": "выкл",
        "status.label.endpoint": "эндпоинт",
        "status.label.format": "формат",
        "status.label.url": "url",
        "status.label.model": "модель",
        "status.label.api_key_type": "тип ключа",
        "status.label.api_key": "api-ключ",
        "status.label.auth": "авторизация",
        "status.label.reasoning": "рассуждения",
        "status.label.mode": "режим",
        "status.label.language": "язык",
        "status.label.chat": "чат",
        "status.label.context": "контекст",
        "status.label.messages": "сообщений",
        "status.label.tokens": "токенов",
        "status.context_none": "(нет)",
        "new.conversation": "  новый разговор",
        "lang.unknown": "  неизвестный язык {wanted!r} — попробуйте en, ru или auto",
        "lang.set": "  язык интерфейса ",
        "lang.auto_label": "авто — как по умолчанию",
        # -- vmpc/commands/mode.py -------------------------------------------
        "mode.custom_suffix": "  свой",
        "mode.menu_hint": "  ·  /mode edit ИМЯ  ·  /mode remove ИМЯ  ·  /mode off",
        "mode.no_mode_named": "  нет режима с именем {name!r}",
        "mode.list_hint": " — список режимов",
        "mode.unlocks_label": "  открывает  ",
        "mode.no_prompt_placeholder": "(промпта нет — используется стандартный, как есть)",
        "mode.unlocked_hint": "  открыты новые команды — ",
        "mode.already_default": "  уже используется стандартный промпт",
        "mode.off": "  режим выключен",
        "mode.off_suffix": " — возврат к стандартному промпту",
        "mode.field_name": "имя",
        "mode.field_name_placeholder": "reviewer",
        "mode.field_description": "описание",
        "mode.field_description_placeholder": "для чего этот режим",
        "mode.field_prompt": "промпт",
        "mode.field_prompt_placeholder": "как модель должна отвечать",
        "mode.default_description": "свой режим",
        "mode.cancelled_no_prompt": "  отменено — режим без промпта ничего не делает",
        "mode.confirm_unlock_dev": "Открыть команды разработчика в этом режиме?",
        "mode.saved": " сохранён — наберите его, чтобы переключиться",
        "mode.built_in": "  /{name} встроен — ",
        "mode.write_own_hint": " напишите свой",
        "mode.no_custom_named": "  нет своего режима с именем {name!r}",
        "mode.cancelled_empty_prompt": "  отменено — пустой промпт",
        "mode.updated": "  ✔ /{name} обновлён",
        "mode.removed": "  удалён /{name}",
        # -- vmpc/commands/model.py ------------------------------------------
        "model.picker_add_label": "+ ввести имя",
        "model.picker_add_desc": "добавить вручную",
        "model.picker_probe_label": "⌕ подбор",
        "model.picker_probe_desc": "перебрать известные имена с этим ключом",
        "model.picker_scan_label": "↻ спросить эндпоинт",
        "model.picker_scan_desc": "повторить GET /models",
        "model.picker_title": "Модель для {name}",
        "model.set": "  модель ",
        "model.field_model": "модель:",
        "model.field_model_placeholder": "точное имя, ожидаемое эндпоинтом",
        "model.already_saved": "  уже сохранено: {name}",
        "model.saved_on": "  сохранено для ",
        "model.which_one": "  какую? /model rm ИМЯ",
        "model.not_saved": "  не сохранено: {name}",
        "model.forgot": "  забыто ",
        "model.still_using": "  всё ещё используется — ",
        "model.to_switch": " чтобы переключить",
        "model.nothing_saved": "  ничего не сохранено, и эндпоинт не ответил",
        "model.saved_label": "сохранено",
        "model.advertised_label": "заявлено",
        "model.did_not_advertise": "  {name} не сообщил список моделей",
        "model.probe_hint": "  /model probe — выяснить перебором",
        "model.new_label": " новых",
        "model.advertised_sep": " заявлено · ",
        "model.probe_header": "  подбор ",
        "model.probe_against": " имён для ",
        "model.probe_requests": "{n} запросов, по одному токену · esc — остановить",
        "model.confirm_send": "Отправить?",
        "model.cancelled": "  отменено",
        "model.stopping_key": "    стоп — это ответ про ключ, а не про имя",
        "model.too_many_failures": "    слишком много ошибок — стоп",
        "model.saved_summary": "  сохранено ",
        "model.using_sep": " · используется ",
        "model.asked": "{n} запрошено",
        "model.label.available": "доступно",
        "model.label.rejected": "отклонено",
        "model.label.unclear": "неясно",
        "model.label.failed": "ошибка",
        "model.label.not_sent": "не отправлено",
        "model.cannot_read": "  ✖ не удалось прочитать {path}: {exc}",
        # -- vmpc/ui/picker.py ------------------------------------------------
        "picker.select_hint": "↑↓ переместить · enter выбрать · esc отмена",
        "picker.multiline_hint": "alt+enter — новая строка · enter — готово · esc отмена",
        "picker.confirm_hint": "enter подтвердить · esc отмена",
        "picker.yes": "да",
        "picker.no": "нет",
        # -- vmpc/config.py: wire/key/auth descriptions ----------------------
        "wire_desc.openai": "/chat/completions, SSE-дельты — OpenAI, Groq, Together, vLLM, LM Studio, OpenRouter",
        "wire_desc.anthropic": "/v1/messages, типизированные SSE-события — Anthropic, шлюзы Bedrock, прокси",
        "keytype_desc.static": "ключ хранится в файле конфигурации",
        "keytype_desc.env": "читается из переменной окружения при запросе",
        "keytype_desc.command": "запускает shell-команду и берёт её stdout (1Password, pass, vault)",
        "auth_desc.raw_suffix": "ключ уже несёт свою схему",
        "auth_desc.none": "без заголовка авторизации — локальные эндпоинты или авторизация через прокси",
        # -- vmpc/commands/api.py ---------------------------------------------
        "api.unknown_verb": "неизвестно: /api {verb}",
        "api.try_hint": "  варианты: add · list · use · edit · remove · test",
        "api.menu_add": "add",
        "api.menu_add_desc": "настроить новый эндпоинт",
        "api.menu_use": "use",
        "api.menu_use_desc": "переключить активный эндпоинт",
        "api.menu_edit": "edit",
        "api.menu_edit_desc": "изменить существующий эндпоинт",
        "api.menu_test": "test",
        "api.menu_test_desc": "отправить тестовый запрос на один токен",
        "api.menu_remove": "remove",
        "api.menu_remove_desc": "удалить эндпоинт",
        "api.menu_title": "API-эндпоинты",
        "api.cancelled": "  отменено",
        "api.saved_to": "  сохранено в {path}",
        "api.summary_added": "добавлен",
        "api.summary_updated": "обновлён",
        "api.edit_which": "Какой эндпоинт изменить?",
        "api.use_which": "Какой эндпоинт использовать?",
        "api.remove_which": "Какой эндпоинт удалить?",
        "api.test_which": "Какой эндпоинт проверить?",
        "api.field_site": "сайт:",
        "api.field_api_key": "api-ключ:",
        "api.key_placeholder_editing": "sk-… (скрыто; ctrl+v — вставить; enter — оставить текущий ключ)",
        "api.key_placeholder_new": "sk-… (скрыто; ctrl+v — вставить)",
        "api.field_env_var": "переменная окружения:",
        "api.field_command": "команда:",
        "api.step_wire_title": "формат API",
        "api.step_keytype_title": "тип api-ключа",
        "api.step_auth_title": "авторизация",
        "api.field_header_name": "имя заголовка:",
        "api.field_model": "модель:",
        "api.field_name": "имя:",
        "api.field_name_placeholder": "как эндпоинт будет называться в /api list",
        "api.field_extra_headers": "доп. заголовки:",
        "api.field_extra_headers_placeholder": "необязательно — имя: значение, через запятую",
        "api.incomplete": "  неполно: {problem}",
        "api.confirm_save_anyway": "Всё равно сохранить?",
        "api.active_label": "  активен: ",
        "api.confirm_remove": "Удалить {name}?",
        "api.removed": "  удалён {name}",
        "api.not_usable": "  непригоден: {problem}",
        "api.testing_arrow": "  → {url}",
        "api.test_empty_response": "(пустой ответ)",
        "api.no_endpoints": "  эндпоинты не настроены",
        "api.label.site": "сайт",
        "api.label.extra_headers": "доп. заголовки",
        "api.err.not_url": "не похоже на URL",
        "api.err.must_http": "URL должен быть http или https",
        "api.err.drop_v1": "уберите /v1 для формата Anthropic — он добавляется автоматически",
        "api.err.header_format": "ожидался формат 'имя: значение', получено {part!r}",
        "api.err.missing_header_name": "не указано имя заголовка в {part!r}",
        "api.err.missing_header_value": "не указано значение для {name!r}",
        # -- vmpc/commands/chats.py -------------------------------------------
        "chats.unknown": "  неизвестно: /chats {action}",
        "chats.hint": "  ·  /chats list  ·  /chats rm",
        "title.rename_label": "  /title ИМЯ",
        "title.rename_desc": "  переименовать  ·  ",
        "title.auto_hint": "/title auto",
        "title.auto_desc": "  спросить модель заново",
        "title.no_name_yet": "  у этого чата пока нет названия",
        "title.no_name_hint": " — или отправьте сообщение, и название придумается само",
        "title.empty_after_clean": "  не осталось ничего, под чем можно сохранить",
        "chats.no_saved": "  сохранённых чатов пока нет",
        "chats.turn": "ход",
        "chats.open_title": "открыть чат",
        "chats.cannot_open": "  не удалось открыть этот чат: {exc}",
        "chats.needs_app": "  /chats требует интерактивное приложение",
        "chats.restored": "восстановлено {n} {turn_noun} · {tokens} токенов",
        "chats.prompt_label": "  промпт  ",
        "chats.naming": "  придумываю название…",
        "chats.nothing_to_name": "  пока нечего называть — сначала что-нибудь спросите",
        "chats.bad_name_response": "  эндпоинт не вернул пригодное название",
        "chats.delete_title": "удалить чат",
        "chats.no_match": "  нет чата, соответствующего {target!r}",
        "chats.confirm_delete": "Удалить {label!r}?",
        "chats.deleted": "  удалён {label}",
        "chats.delete_failed": "  не удалось удалить этот чат",
        "chats.ago_just_now": "только что",
        "chats.ago_minutes": "{n} мин. назад",
        "chats.ago_hours": "{n} ч. назад",
        "chats.ago_days": "{n} дн. назад",
        # -- vmpc/context.py --------------------------------------------------
        "ctx.reason.over_file_limit": "превышен лимит файлов",
        "ctx.reason.binary": "бинарный",
        "ctx.reason.secret": "похоже на секрет",
        "ctx.reason.budget": "бюджет",
        "ctx.reason.unreadable": "не читается ({detail})",
        "ctx.reason.empty": "пустой",
        "ctx.reason.too_big": "слишком большой",
        "ctx.err.not_file_or_folder": "{path} — не файл и не папка",
        "ctx.err.no_path": "путь не указан",
        "ctx.err.cannot_resolve": "не удалось разрешить {target}: {exc}",
        "ctx.err.does_not_exist": "{path} не существует",
        "ctx.err.budget_full": "бюджет контекста уже исчерпан",
        # -- vmpc/commands/context.py -----------------------------------------
        "ctx.which_folder": "  какую папку? /context ПУТЬ",
        "ctx.already_attached": "  уже подключено: {path}",
        "ctx.which_one": "  какой? /context rm ПУТЬ",
        "ctx.not_attached": "  не подключено: {path}",
        "ctx.nothing_attached": "  ничего не подключено",
        "ctx.hint_path": "ПУТЬ — прочитать папку или файл",
        "ctx.detached": "  отключено ",
        "ctx.header_context": "контекст",
        "ctx.header_reloaded": "контекст перечитан",
        "ctx.skipped_label": "  │   пропущено ",
        "ctx.budget_ran_out": "бюджет исчерпан — подключено не всё",
        "ctx.tokens_added": " добавляется в каждый ход · ",
        "ctx.clear_hint": "/context clear",
        "ctx.to_detach": " чтобы отключить",
        # -- vmpc/commands/dev.py ---------------------------------------------
        "dev.no_role_message": "  нет сообщения роли {role} так глубоко",
        "dev.chars_lines": "{chars} симв., {n} {line_noun}",
        "dev.line": "строка",
        "dev.no_reply_rerender": "  нет ответа для повторного рендера",
        "dev.render_header": "  рендер ",
        "dev.sample_label": "пример",
        "dev.last_reply_label": "последний ответ",
        "dev.width_label": " · ширина {width}",
        "dev.post_label": "  POST ",
        "dev.via_label": "  через  ",
        "dev.transport_sdk": "SDK поставщика",
        "dev.transport_httpx": "httpx",
        "dev.credential_error": "  ✖ учётные данные: {detail}",
        "dev.ping_header": "  пинг ",
        "dev.no_content": "  ✖ ничего не пришло",
        "dev.label.total": "всего",
        "dev.label.first_token": "первый токен",
        "dev.label.throughput": "скорость",
        "dev.label.output": "вывод",
        "dev.output_value": "{tokens} токенов, {chars} симв.",
        "dev.palette.color_system": "цветовая система",
        "dev.palette.no_color": "no_color",
        "dev.palette.terminal": "терминал",
        "dev.palette.legacy_windows": "legacy windows",
        "dev.palette.width": "ширина",
        "dev.prompt_header": "  системный промпт",
        "dev.prompt_chars": "  {n} симв.",
        "dev.mode_label": "  режим  ",
        "dev.mode_none": "(нет — только стандартный промпт)",
        "dev.files_label": "  файлы ",
        # -- vmpc/cli.py -------------------------------------------------------
        "cli.no_terminal": "vmpc: интерактивный режим требует терминал.\n  запустите 'vmpc' прямо в терминале, или используйте подкоманду:\n    vmpc chat \"ваш вопрос\"\n    vmpc api list",
        "cli.no_endpoint_named": "vmpc: нет эндпоинта с именем {name!r}",
        "cli.no_saved_chat_matching": "vmpc: нет сохранённого чата, соответствующего {what!r}",
        "cli.nothing_to_send": "vmpc: нечего отправлять",
        "cli.no_endpoint_configured": "vmpc: эндпоинт не настроен — выполните 'vmpc api add'",
        "cli.provider_problem": "vmpc: {name}: {problem}",
        "cli.error_prefix": "vmpc: {error}",
        "cli.error_hint": "  {hint}",
        "cli.context_problem": "vmpc: контекст: {problem}",
        "cli.api_needs_terminal": "vmpc: {label} задаёт вопросы, поэтому нужен терминал.\n  эти работают везде:\n    vmpc api list\n    vmpc api test ИМЯ",
        "cli.endpoint_menu_label": "меню эндпоинтов",
        "cli.no_endpoint_short": "эндпоинт не настроен",
        "cli.unknown_models_action": "vmpc: неизвестное действие 'models' {action!r}",
        "cli.did_not_advertise": "{name} не сообщил список моделей",
        "cli.models_probe_hint": "  vmpc models probe",
        "cli.models_probe_hint_suffix": "  — выяснить перебором",
        "cli.probe_needs_terminal": "vmpc: 'models probe' спрашивает перед отправкой, поэтому нужен терминал.\n  запустите в терминале, либо используйте '/model probe' внутри vmpc",
        "cli.which_chat": "vmpc: какой чат? передайте id из 'vmpc chats'",
        "cli.no_saved_chat": "vmpc: нет сохранённого чата, соответствующего {target!r}",
        "cli.could_not_delete": "vmpc: не удалось удалить {id}",
        "cli.deleted": "удалён {label}",
        "cli.unknown_chats_action": "vmpc: неизвестное действие 'chats' {action!r}",
        "cli.no_saved_chats": "сохранённых чатов пока нет",
        # -- vmpc/streaming/controller.py -------------------------------------
        "stream.thinking": "Думаю",
        # -- vmpc/render/status.py --------------------------------------------
        "status.interrupt_hint": "Esc — прервать",
        "status.tok_suffix": " ток",
    },
}
